<!-- 2020-01-17
1) "Defer offscreen images for the Slick slider of the home page":
https://github.com/tradefurniturecompany/site/issues/153
2) https://kenwheeler.github.io/slick
2021-08-07 "Update the collections slider on the front page": https://github.com/tradefurniturecompany/site/issues/226 -->
<?php use TFC\Core\B\Home\Slider as B; /** @var B $block */ /** @var B $b */ $b = $block; ?>
<div class='widget block block-static-block'>
	<div class='furniture-links-wrapper'>
		<div class='furniture-links furniture-links-double'>
			<div class='furniture-link'>
				<?= $b->i('LIGHT DAKOTA') ?>
				<?= $b->i('DARK DAKOTA', 'dakota') ?>
			</div>
			<div class='furniture-link'>
				<?= $b->i('LIGHT MANGO', 'mango-light') ?>
				<?= $b->i('DARK MANGO', 'mango-dark') ?>
			</div>
			<div class='furniture-link'>
				<?= $b->i('LIGHT VINTAGE') ?>
				<?= $b->i('DARK VINTAGE', 'vintage') ?>
			</div>
			<div class='furniture-link'>
				<?= $b->i('CUBE LIGHT') ?>
				<?= $b->i('JALI LIGHT') ?>
			</div>
			<div class='furniture-link'>
				<?= $b->i('CUBE NATURAL') ?>
				<?= $b->i('JALI NATURAL') ?>
			</div>
			<div class='furniture-link'>
				<?= $b->i('CUBE HONEY', 'cube-dark') ?>
				<?= $b->i('JALI HONEY', 'jali-dark') ?>
			</div>
			<div class='furniture-link'>
				<?= $b->i('LIGHT RETRO CHIC') ?>
				<?= $b->i('DARK RETRO CHIC', 'retro-chic') ?>
			</div>
			<div class='furniture-link'>
				<?= $b->i('LIGHT VINTAGE MANGO') ?>
				<?= $b->i('VINTAGE MANGO') ?>
			</div>
			<div class='furniture-link'>
				<?= $b->i('CUBA LIGHT') ?>
				<?= $b->i('RECLAIMED INDIAN FURNITURE') ?>
			</div>
			<div class='furniture-link'>
				<?= $b->i('CUBA NATURAL') ?>
				<?= $b->i('RATTAN') ?>
			</div>
			<div class='furniture-link'>
				<?= $b->i('CUBA HONEY', 'cuba-dark') ?>
				<?= $b->i('INDUSTRIAL FURNITURE') ?>
			</div>
<!-- 2022-11-09 "Update the home slider (2022-11-09)": https://github.com/tradefurniturecompany/core/issues/43 -->
			<div class='furniture-link'>
				<?= $b->i('GEO MANGO') ?>
				<?= $b->i('GEO MANGO LIGHT') ?>
			</div>
			<div class='furniture-link'>
				<?= $b->i('BLOCK MANGO') ?>
				<?= $b->i('BLOCK MANGO LIGHT') ?>
			</div>
		</div>
		<p class='category-links-arrows furniture-links-arrows'>
			<?=
				df_cc_n(
					df_tag('img', df_clean([
						'alt' => 'previous'
						,'class' => 'furniture-links-arrows--prev'
						,'src' => $b->getViewFileUrl('images/prev.png')
					]))
					,df_tag('img', df_clean([
						'alt' => 'Next'
						,'class' => 'furniture-links-arrows--next'
						,'src' => $b->getViewFileUrl('images/next.png')
					]))
				)
			?>
		</p>
	</div>
</div>
<script type='text/javascript'>
require(['jquery', 'slick', 'domReady!'], function($) {
	var done = false;
	var $w = $(window);
	var $c = $('.furniture-links-double');
	// 2020-03-19 «Jquery detect which block is visible on screen when scroll»: https://stackoverflow.com/a/29429610
	var visible = function() {
		var elementTop = $c.offset().top;
		var elementHeight = $c.height();
		var containerTop = $w.scrollTop();
		return 0 < elementTop - containerTop + elementHeight && elementTop - containerTop < $w.height();
	};
	var init = function() {done = true; $c.slick({
		arrows: true,
		autoplay: true,
		dots: false,
		infinite: true,
		lazyLoad: 'ondemand',
		nextArrow: '.furniture-links-arrows--next',
		prevArrow: '.furniture-links-arrows--prev',
		responsive: [
			{breakpoint: 1280, settings: {slidesToScroll: 1, slidesToShow: 3}},
			{breakpoint: 768, settings: {slidesToScroll: 1, slidesToShow: 3}},
			{breakpoint: 600, settings: {slidesToScroll: 1, slidesToShow: 1}}
		],
		slidesToScroll: 1,
		slidesToShow: 3,
		speed: 1000
	});};
	var check = function() {done || !visible() || init();};
	$w.scroll(check);
	check();
});
</script>