<!-- 2020-01-17
1) "Defer offscreen images for the Slick slider of the home page":
https://github.com/tradefurniturecompany/site/issues/153
2) https://kenwheeler.github.io/slick
2021-08-07 "Update the collections slider on the front page": https://github.com/tradefurniturecompany/site/issues/226 -->
<?php use TFC\Core\B\Home\Slider as B; /** @var B $block */ /** @var B $b */ $b = $block; ?>
<div class='widget block block-static-block'>
	<div class='furniture-links-wrapper'>
		<div class='furniture-links furniture-links-double'>
			<div class='furniture-link'>
				<?= $b->i('light-dakota', 'light_dakota') ?>
				<p class='heading'>LIGHT DAKOTA</p>
				<?= $b->i('dakota', 'dakota') ?>
				<p class='heading'>DARK DAKOTA</p>
			</div>
			<div class='furniture-link'>
				<?= $b->i('mango-light', 'mango_light') ?>
				<p class='heading'>LIGHT MANGO</p>
				<?= $b->i('mango-dark', 'mango_dark') ?>
				<p class='heading'>DARK MANGO</p>
			</div>
			<div class='furniture-link'>
				<?= $b->i('light-vintage', 'light_vintage') ?>
				<p class='heading'>LIGHT VINTAGE</p>
				<?= $b->i('vintage', 'vintage') ?>
				<p class='heading'>DARK VINTAGE</p>
			</div>
			<div class='furniture-link'>
				<?= $b->i('cube-light', 'cube_light') ?>
				<p class='heading'>CUBE LIGHT</p>
				<?= $b->i('jali-light', 'jali_light') ?>
				<p class='heading'>JALI LIGHT</p>
			</div>
			<div class='furniture-link'>
				<?= $b->i('cube-natural', 'cube_natural') ?>
				<p class='heading'>CUBE NATURAL</p>
				<?= $b->i('jali-natural', 'jali_natural') ?>
				<p class='heading'>JALI NATURAL</p>
			</div>
			<div class='furniture-link'>
				<?= $b->i('cube-dark', 'cube_honey') ?>
				<p class='heading'>CUBE HONEY</p>
				<?= $b->i('jali-dark', 'jali_honey') ?>
				<p class='heading'>JALI HONEY</p>
			</div>
			<div class='furniture-link'>
				<?= $b->i('light-retro-chic', 'Light_Retro_CHic', 500, 350, 'Light Retro Chic') ?>
				<p class='heading'>LIGHT RETRO CHIC</p>
				<?= $b->i('retro-chic', 'retro_chic') ?>
				<p class='heading'>DARK RETRO CHIC</p>
			</div>
			<div class='furniture-link'>
				<?= $b->i('light-vintage-mango', 'light_vintage_mango') ?>
				<p class='heading'>LIGHT VINTAGE MANGO</p>
				<?= $b->i('vintage-mango', 'vintage_mango') ?>
				<p class='heading'>VINTAGE MANGO</p>
			</div>
			<div class='furniture-link'>
				<?= $b->i('cuba-light', 'cuba_light') ?>
				<p class='heading'>CUBA LIGHT</p>
				<?= $b->i('reclaimed-indian-furniture', 'reclaimed_indian_furniture') ?>
				<p class='heading'>RECLAIMED INDIAN FURNITURE</p>
			</div>
			<div class='furniture-link'>
				<?= $b->i('cuba-natural', 'cuba_natural') ?>
				<p class='heading'>CUBA NATURAL</p>
				<?= $b->i('rattan', 'rattan') ?>
				<p class='heading'>RATTAN</p>
			</div>
			<div class='furniture-link'>
				<?= $b->i('cuba-dark', 'cuba_honey') ?>
				<p class='heading'>CUBA HONEY</p>
				<?= $b->i('industrial-furniture', 'industrial') ?>
				<p class='heading'>INDUSTRIAL FURNITURE</p>
			</div>
<!-- 2022-11-09 "Update the home slider (2022-11-09)": https://github.com/tradefurniturecompany/core/issues/43 -->
			<div class='furniture-link'>
				<?= $b->i('geo-mango', 'geo_mango') ?>
				<p class='heading'>GEO MANGO</p>
				<?= $b->i('geo-mango-light', 'geo_mango_light') ?>
				<p class='heading'>GEO MANGO LIGHT</p>
			</div>
			<div class='furniture-link'>
				<?= $b->i('block-mango', 'block_mango') ?>
				<p class='heading'>BLOCK MANGO</p>
				<?= $b->i('block-mango-light', 'block_mango_light') ?>
				<p class='heading'>BLOCK MANGO LIGHT</p>
			</div>
		</div>
		<p class='category-links-arrows furniture-links-arrows'>
			<?=
				df_cc_n(
					df_tag('img', df_clean([
						'alt' => 'previous'
						,'class' => 'furniture-links-arrows--prev'
						,'src' => $b->getViewFileUrl('images/prev.png')
					]))
					,df_tag('img', df_clean([
						'alt' => 'Next'
						,'class' => 'furniture-links-arrows--next'
						,'src' => $b->getViewFileUrl('images/next.png')
					]))
				)
			?>
		</p>
	</div>
</div>
<script type='text/javascript'>
require(['jquery', 'slick', 'domReady!'], function($) {
	var done = false;
	var $w = $(window);
	var $c = $('.furniture-links-double');
	// 2020-03-19 «Jquery detect which block is visible on screen when scroll»: https://stackoverflow.com/a/29429610
	var visible = function() {
		var elementTop = $c.offset().top;
		var elementHeight = $c.height();
		var containerTop = $w.scrollTop();
		return 0 < elementTop - containerTop + elementHeight && elementTop - containerTop < $w.height();
	};
	var init = function() {done = true; $c.slick({
		arrows: true,
		autoplay: true,
		dots: false,
		infinite: true,
		lazyLoad: 'ondemand',
		nextArrow: '.furniture-links-arrows--next',
		prevArrow: '.furniture-links-arrows--prev',
		responsive: [
			{breakpoint: 1280, settings: {slidesToScroll: 1, slidesToShow: 3}},
			{breakpoint: 768, settings: {slidesToScroll: 1, slidesToShow: 3}},
			{breakpoint: 600, settings: {slidesToScroll: 1, slidesToShow: 1}}
		],
		slidesToScroll: 1,
		slidesToShow: 3,
		speed: 1000
	});};
	var check = function() {done || !visible() || init();};
	$w.scroll(check);
	check();
});
</script>