<!-- 2020-05-15
"Hide the text between sliders into a collapsible box on narrow screens": https://github.com/tradefurniturecompany/core/issues/29
2021-08-16 "Change the wording on the homepage": https://github.com/tradefurniturecompany/site/issues/233 -->
<div class='tfc-welcome'>
	<div class='tfc-contents tfc-hidden-ge768'>
		<p>Welcome to Trade Furniture Company, the market leaders in <a title='Mango' href='<?= df_url("mango-furniture") ?>'>Mango</a> and <a title='Sheesham' href='<?= df_url("sheesham-furniture") ?>'>Sheesham</a> 100% solid wood furniture.</p>
		<p>We manufacture high quality solid wood furniture to our own design and specification. Our collections boast a huge range of solid wood furniture that will make your house a truly beautiful home.</p>
		<p>Whether you want beautiful wooden furniture for the whole house or you are shopping for a specific room we will have what you need at an unbeatable price. * Our price match is based on any other outlet using the same size dimensions.</p>
	</div>
	<div class='tfc-toggle closed'><div>…</div></div>
</div>
<script type='text/javascript'>
require(['jquery', 'domReady!'], function($) {
	var $c = $('.tfc-welcome');
	var $text = $('.tfc-contents', $c);
	var $toggle = $('.tfc-toggle', $c);
	var $toggleLabel = $toggle.children('div');
	$toggle.click(function() {
		var c = 'tfc-hidden-ge768';
		$text.toggleClass(c);
		var hidden = $text.hasClass(c);
		$toggleLabel.text(hidden ? '…' : '×');
		$toggle.toggleClass('closed', hidden);
	});
});
</script>